config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :validators
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/email_log.rb
class EmailLog < ApplicationRecord
  # Disable STI
  self.inheritance_column = :_type_disabled

  belongs_to :record, polymorphic: true
end

app/models/exit_request.rb
class ExitRequest < ApplicationRecord
  has_many :validators

  def all_validators_exited?
    validators.pluck(:status).all?('exited')
  end

  def sent_completed_email?
    EmailLog.where(record: self, type: 'eth_staking.exit_request_completed').exists?
  end

  def check_complete_status
    self.with_lock do
      if status != 'complete' && all_validators_exited?
        update(status: 'complete')
        EmailLog.create(record: self, type: 'eth_staking.exit_request_completed') unless sent_completed_email?
      end
    end
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :validator
end

app/models/validator.rb
class Validator < ApplicationRecord
  self.primary_key = :pubkey

  belongs_to :exit_request, optional: true

  after_update { exit_request&.check_complete_status if status == 'exited' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy!

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:txn_hash, :validator_id)
    end
end

app/controllers/validators_controller.rb
class ValidatorsController < ApplicationController
  before_action :set_validator, only: %i[ show edit update destroy ]

  # GET /validators or /validators.json
  def index
    @validators = Validator.all
  end

  # GET /validators/1 or /validators/1.json
  def show
  end

  # GET /validators/new
  def new
    @validator = Validator.new
  end

  # GET /validators/1/edit
  def edit
  end

  # POST /validators or /validators.json
  def create
    @validator = Validator.new(validator_params)

    respond_to do |format|
      if @validator.save
        format.html { redirect_to validator_url(@validator), notice: "Validator was successfully created." }
        format.json { render :show, status: :created, location: @validator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @validator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /validators/1 or /validators/1.json
  def update
    respond_to do |format|
      if @validator.update(validator_params)
        format.html { redirect_to validator_url(@validator), notice: "Validator was successfully updated." }
        format.json { render :show, status: :ok, location: @validator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @validator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /validators/1 or /validators/1.json
  def destroy
    @validator.destroy!

    respond_to do |format|
      format.html { redirect_to validators_url, notice: "Validator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_validator
      @validator = Validator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def validator_params
      params.fetch(:validator, {}).permit(:pubkey, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/validators_helper.rb
module ValidatorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomId</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :txn_hash, style: "display: block" %>
    <%= form.text_field :txn_hash %>
  </div>

  <div>
    <%= form.label :validator_id, style: "display: block" %>
    <%= form.text_field :validator_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Txn hash:</strong>
    <%= transaction.txn_hash %>
  </p>

  <p>
    <strong>Validator:</strong>
    <%= transaction.validator_id %>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>

app/views/validators/_form.html.erb
<%= form_with(model: validator) do |form| %>
  <% if validator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(validator.errors.count, "error") %> prohibited this validator from being saved:</h2>

      <ul>
        <% validator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>

    <div>
      <%= form.label :pubkey %>
      <%= form.text_field :pubkey %>
    </div>

    <div>
      <%= form.label :status %>
      <%= form.text_field :status %>
    </div>

    <%= form.submit %>
  </div>
<% end %>

app/views/validators/_validator.html.erb
<div id="<%= dom_id validator %>">
  <p>Pubkey: <%= validator.pubkey %></p>

  Status: <%= validator.status %>
</div>

app/views/validators/edit.html.erb
<h1>Editing validator</h1>

<%= render "form", validator: @validator %>

<br>

<div>
  <%= link_to "Show this validator", @validator %> |
  <%= link_to "Back to validators", validators_path %>
</div>

app/views/validators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Validators</h1>

<div id="validators">
  <% @validators.each do |validator| %>
    <%= render validator %>
    <p>
      <%= link_to "Show this validator", validator %>
    </p>
  <% end %>
</div>

<%= link_to "New validator", new_validator_path %>

app/views/validators/new.html.erb
<h1>New validator</h1>

<%= render "form", validator: @validator %>

<br>

<div>
  <%= link_to "Back to validators", validators_path %>
</div>

app/views/validators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @validator %>

<div>
  <%= link_to "Edit this validator", edit_validator_path(@validator) %> |
  <%= link_to "Back to validators", validators_path %>

  <%= button_to "Destroy this validator", @validator, method: :delete %>
</div>